name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar y desplegar por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_PROJECT_PATH }}
            git pull origin main
            for f in ${{ secrets.VPS_PROJECT_PATH }}/todo-app/backend/migrations/*.sql; do PGPASSWORD='${{ secrets.DB_PASSWORD }}' psql -U todo_user -d todo_db -h localhost -f "$f"; done
            cd todo-app/backend
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart todoapp
            sudo cp -r ${{ secrets.VPS_PROJECT_PATH }}/todo-app/frontend/* /var/www/todoapp/
            sudo chown -R www-data:www-data /var/www/todoapp